"use client"
import Navbar from '@/components/Navbar'
import { Toaster } from 'react-hot-toast'
import './globals.css'
import { UserContext } from '../lib/context';
import { useUserData } from '../lib/hooks';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const userData = useUserData();

  return (
    <html lang="en">
      <>
        <body>
          <UserContext.Provider value={userData}>
            <Navbar />
            {children}
            <Toaster />
          </UserContext.Provider>
        </body>
      </>
    </html>
  )
}
